name: "maths_points_game"
description: "Implementation of squares conquest game."
publish_to: "none"

version: 3.0.0+3

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  flutter_bloc: ^8.1.3
  flutter_riverpod: ^2.4.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  get_it: ^8.0.2
  flutter_colorpicker: ^1.1.0
  gif_view: ^0.4.4
  sqflite_common_ffi: ^2.3.6
  intl: ^0.20.2
  riverpod: ^2.6.1

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  # rename: ^3.0.2 # Use the latest version
  flutter_lints: ^4.0.0
flutter:
  assets:
    - "assets/maths_points_game_logo.gif"
  uses-material-design: true
flutter_icons:
  android: true
  ios: true
  image_path: "assets/maths_points_game_logo.png" # Chemin de votre icône

